server:
  port: 8080
#spring的配置
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource #数据源为druid
    driver-class-name: com.mysql.jdbc.Driver #数据库驱动
    url: jdbc:mysql://192.168.4.10:3306/vue?useSSL=false&useUnicode=true&characterEncoding=utf-8&servetTimeZone=Asia/Shanghai
    username: pupumall_pre
    password: V1e*tSaUlBeYB2u2
mybatis:
  mapper-locations : classpath:com/example/demomb/mapper/*.xml
#pagehelper plugins 用于分页
pagehelper:
  # 分页的数据来源
  helper-dialect: mysql
  # 启用合理化，如果pageNum<1会查询第一页，如果pageNum>pages会查询最后一页
  reasonable: false
  # 支持通过 Mapper 接口参数来传递分页参数，默认值false
  support-methods-arguments: true
  #用于从对象中根据属性名取值，可以配置 pageNum，pageSize，count，pageSizeZero，reasonable，
  #不配置映射的用默认值，默认值为 pageNum=pageNum；pageSize=pageSize；count=countSql；reasonable=reasonable；
  params: count=countSql